DROP DATABASE IF EXISTS trust_pilot;
CREATE DATABASE trust_pilot;
USE trust_pilot;
CREATE TABLE Category (    category_id int NOT NULL AUTO_INCREMENT,    name VARCHAR(45),    url VARCHAR(2000),    PRIMARY KEY (category_id));
CREATE TABLE Business (    business_id int NOT NULL AUTO_INCREMENT,    category_id int NOT NULL,    name VARCHAR(255),    score float,    reviews int,    url VARCHAR(2000),    PRIMARY KEY (business_id, name),    FOREIGN KEY (category_id) REFERENCES Category(category_id));
CREATE TABLE User_details (    user_id int NOT NULL AUTO_INCREMENT,    user_name VARCHAR(255),    user_location VARCHAR(45),    primary KEY (user_id));
CREATE TABLE Review (    review_id int NOT NULL AUTO_INCREMENT,    business_id int,    user_id int,    score float,    url VARCHAR(2000),    review_date timestamp,    PRIMARY KEY (review_id),    FOREIGN KEY (business_id) REFERENCES Business(business_id),    FOREIGN KEY (user_id) REFERENCES User_details(user_id));
CREATE TABLE Review_text (    review_id int NOT NULL AUTO_INCREMENT,    title VARCHAR(255),    text VARCHAR(2000),    primary KEY (review_id),    FOREIGN KEY (review_id) REFERENCES Review(review_id));
CREATE TABLE Review_sentiment (Review_id int NOT NULL AUTO_INCREMENT,                               positive VARCHAR(255),                               neutral VARCHAR(2000),                               negative VARCHAR(2000),                               primary KEY (review_id));
INSERT INTO Category (name, url) VALUES ("Animals & Pets", "https://www.trustpilot.com/categories/animals_pets?numberofreviews=0&status=all&timeperiod=0&page=1");
INSERT INTO Business (category_id, name, url, score, reviews) VALUES (1, "Boomerang Pet ID Tags", "https://www.trustpilot.com/review/www.boomerangtags.com", 5.0, 9836);
INSERT INTO Business (category_id, name, url, score, reviews) VALUES (1, "HealthySmiles Pet Dental", "https://www.trustpilot.com/review/healthysmiles.pet", 5.0, 939);
INSERT INTO Business (category_id, name, url, score, reviews) VALUES (1, "PopArtYou", "https://www.trustpilot.com/review/popartyou.com", 5.0, 367);
INSERT INTO Business (category_id, name, url, score, reviews) VALUES (1, "DogWatch Hidden Fences", "https://www.trustpilot.com/review/dogwatch.com", 4.9, 3148);
INSERT INTO Business (category_id, name, url, score, reviews) VALUES (1, "Paw Print Genetics", "https://www.trustpilot.com/review/pawprintgenetics.com", 4.9, 2461);
INSERT INTO Business (category_id, name, url, score, reviews) VALUES (1, "Vetpetni", "https://www.trustpilot.com/review/vetpetni.co.uk", 4.9, 1457);
INSERT INTO Business (category_id, name, url, score, reviews) VALUES (1, "4 Corners Cannabis CBD", "https://www.trustpilot.com/review/4cornerscannabis.com", 4.9, 1091);
INSERT INTO Business (category_id, name, url, score, reviews) VALUES (1, "Champlain Valley Organics LLC - Vermont Pure CBD", "https://www.trustpilot.com/review/vermontpurecbd.com", 4.9, 802);
INSERT INTO Business (category_id, name, url, score, reviews) VALUES (1, "Nuvet Labs", "https://www.trustpilot.com/review/www.nuvet.com", 4.9, 718);
INSERT INTO Business (category_id, name, url, score, reviews) VALUES (1, "CollarTags", "https://www.trustpilot.com/review/collartags.com", 4.9, 666);
INSERT INTO Business (category_id, name, url, score, reviews) VALUES (1, "Petals and Tails", "https://www.trustpilot.com/review/petalsandtails.com", 4.9, 472);
INSERT INTO Business (category_id, name, url, score, reviews) VALUES (1, "Pet Rebellion", "https://www.trustpilot.com/review/petrebellion.co.uk", 4.9, 249);
INSERT INTO Business (category_id, name, url, score, reviews) VALUES (1, "Life's Abundance", "https://www.trustpilot.com/review/lifesabundance.com", 4.8, 9164);
INSERT INTO Business (category_id, name, url, score, reviews) VALUES (1, "BarkBox", "https://www.trustpilot.com/review/barkbox.com", 4.8, 7756);
INSERT INTO Business (category_id, name, url, score, reviews) VALUES (1, "Dog Tag Art", "https://www.trustpilot.com/review/dogtagart.com", 4.8, 3776);
INSERT INTO Business (category_id, name, url, score, reviews) VALUES (1, "PetCanva", "https://www.trustpilot.com/review/petcanva.com", 4.8, 3020);
INSERT INTO Business (category_id, name, url, score, reviews) VALUES (1, "Valley Vet Supply", "https://www.trustpilot.com/review/www.valleyvet.com", 4.8, 2751);
INSERT INTO Business (category_id, name, url, score, reviews) VALUES (1, "Pawshake | Dog sitting, Cat sitting, Pet Sitting, Dog Walking", "https://www.trustpilot.com/review/pawshake.com", 4.8, 2482);
